//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply_insTB
    {
        public int Application_id { get; set; }
        public int Job_Id { get; set; }
        public int Company_Id { get; set; }
        public int User_Id { get; set; }
        public string Rsume { get; set; }
        public System.DateTime Apply_Date { get; set; }
        public string Status { get; set; }
    }
}
