//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_RegTab
    {
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public int User_Age { get; set; }
        public string User_Address { get; set; }
        public string User_Phone { get; set; }
        public string User_Mail { get; set; }
        public string User_Location { get; set; }
        public string User_Skill { get; set; }
        public string User_Qualification { get; set; }
        public int User_Experiance { get; set; }
        public System.DateTime User_DOB { get; set; }
    }
}
